# This file sets up configuration parameters for sensor communication, like serial ports and baud rates
---
Picarro Gas:
  serial port: "COM9" # Nothing
  baud rate: 19200
Picarro Water:
  serial port: "COM9" # Nothing
  baud rate: 19200
Laser Distance Sensor:
  serial port: "COM6" # lab computer
  baud rate: 19200
Abakus Particle Counter:
  serial port: "COM4" # lab computer
  baud rate: 38400
Flowmeter SLI2000 (Green):
  serial port: "COM3" # lab computer
  baud rate: 115200
Flowmeter SLS1500 (Black):
  serial port: "COM5" # lab computer
  baud rate: 115200
Bronkhorst Pressure:
  serial port: "COM7" # lab computer
  baud rate: 38400
Melthead:
  serial port: "COM7"
  baud rate: 38400