# This file sets up the dictionary for data management / live plotting buffer.
#
# IMPORTANT - the dictionary keys ("Time (epoch)" and "Data") must exist and be spelled correctly. If you want to eliminate all
#   the data channels from a sensor, just comment out the whole sensor.
#
# ALSO IMPORTANT - if you've already taken some data in a day and then want to change what sensors are active here, go into the
#   data_saving.yaml config file and add a data suffix. This will create a new file with an updated header, so you don't run
#   the risk of saving data to the incorrect header.
---
Picarro Gas:
  Time (epoch): []
  Data:
    CO2: []
    CH4: []
    CO: []
    H2O: []
# Picarro Water:
#   Time (epoch): []
#   Data:
#     H2O (ppm): []
#     Delta_18_16 (%o): []
#     Delta_D_H (%o): []
Laser Distance Sensor:
  Time (epoch): []
  Data:
    Distance (cm): []
    Temperature (C): []
Abakus Particle Counter:
  Time (epoch): []
  Data:
    Total Counts: []
  Other:
    Bins: []
    Counts: []
Flowmeter:
  Time (epoch): []
  Data:
    SLI2000 (uL/min): []
    SLS1500 (mL/min): []
  Other:
    Samples Per Query: 15
Bronkhorst Pressure:
  Time (epoch): []
  Data:
    Setpoint (mbar a): []
    Measurement (%): []
    Measurement (mbar a): []
    Temperature (C): []
# Melthead:
#   Time (epoch): []
#   Data:
#     Dummy key: []
  
